### ISSUE TITLE
Text Changes

### ISSUE THREAD

**Issue by juanmontauk** [Montauk/sti-motos#1]
Reemplazar el texto **"Somos una empresa"** por:

> Somos una empresa lider en el comercio electronico, mas de 60.000 operaciones exitosas en Mercadolibre nos convierten en uno de los mejores vendedores de todo el sitio. Nuestra estructura que se adapta constatemente a las nuevas tecnologias  y nuestro personal altamente capacitado, nos hace unicos cuando se habla de ventas online.

También en **Quienes Somos**.

**Comment by juanmontauk** [comment]
Reemplazar en el banner de pagos & envios **Con MercadoPago** por:

> Ver todas las promociones.

**Comment by juanmontauk** [comment]
Reemplazar en el banner de pagos & envios **Envios por encomienda** por:

> Hacemos envíos a todo el país.

**Comment by juanmontauk** [comment]
Cambiar la frase  de las pelotas por:

> Sea lo que sea es mejor si vas rodando.

**Comment by juanmontauk** [comment]
En planes de financiación (Pagos & Envíos):

En 12 cuotas va **de Juev. a Sáb.**
Lo mismo en 18 cuotas.

**Comment by Keevarleo** [comment]
Solved.
