### ISSUE TITLE
Modificación Menor

### ISSUE THREAD

**Issue by juanmontauk** [Montauk/sti-motos#3]
Agregar un botón de 'Como Comprar' al lado del banner de Preguntas Frecuentes (en el Home), respetando el diseño.
Debajo de 'Sea lo que sea es mejor si vas rodando'.
_Que diga: "Comprá en nuestra tienda en pocos pasos" y en el botón que diga 'Cómo Comprar'._

**Comment by Keevarleo** [comment]
Solved.
